services:
  app:
    build: .
    container_name: lemp_node
    ports:
      - "80:80"
      - "443:443"
      - "5050:5050"
    volumes:
      - ./www:/var/www/html
      - ./conf/default.conf:/etc/nginx/nginx.conf
      - ./.env:/var/www/.env
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_logs:/var/log/pgadmin
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PASSWORD_ROOT: ${DB_PASSWORD_ROOT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - lempnet
    restart: always
    depends_on:
      - db
      - postgres

  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lempnet
    restart: always

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lempnet
    restart: always

networks:
  lempnet:
    driver: bridge

volumes:
  mariadb_data:
  postgres_data:
  pgadmin_data:
  pgadmin_logs: